// This file was auto-generated by prisma-generator-typescript-interfaces

export type CarType = 'Hatchback' | 'Sedan' | 'SUV' | 'MUV' | 'Coupe' | 'Convertible';

export type CarSteering = 'Manual' | 'Auto';

export interface User {
  id: number;
  createdAt: Date;
  name: string;
  lastname?: string | null;
  email: string;
  phone?: string | null;
  address?: string | null;
  city?: string | null;
  avatar?: string | null;
}

export interface Car {
  id: number;
  createdAt: Date;
  brand: string;
  model: string;
  description?: string | null;
  rating: Decimal;
  type: CarType;
  capacity: number;
  steering: CarSteering;
  gasoline: number;
  price: Decimal;
  discount: number;
  images: string[];
}

export interface Review {
  id: number;
  createdAt: Date;
  title: string;
  content: string;
  rating: number;
  userId: number;
  carId: number;
}

export interface Order {
  id: number;
  createdAt: Date;
  name: string;
  phone: string;
  address: string;
  city: string;
  pickup: JsonValue;
  dropoff: JsonValue;
  payment: JsonValue;
  price: Decimal;
  userId: number;
  carId: number;
}

export interface Favorite {
  createdAt: Date;
  userId: number;
  carId: number;
}

export interface Notification {
  id: number;
  createdAt: Date;
  text: string;
  isSeen: boolean;
  userId: number;
}

export interface CarView {
  createdAt: Date;
  userId: number;
  carId: number;
}

type Decimal = { valueOf(): string };

type JsonValue = string | number | boolean | { [key in string]?: JsonValue } | Array<JsonValue> | null;
