// This file was auto-generated by prisma-generator-typescript-interfaces

import type { Decimal } from 'decimal.js';

export type CarType = 'Hatchback' | 'Sedan' | 'SUV' | 'MUV' | 'Coupe' | 'Convertible';

export type CarSteering = 'Manual' | 'Auto';

export interface UserDBModel {
  id: number;
  createdAt: Date;
  email: string;
  password: string;
  name?: string | null;
  lastname?: string | null;
  phone?: string | null;
  address?: string | null;
  city?: string | null;
  avatar?: string | null;
}

export interface CarDBModel {
  id: number;
  createdAt: Date;
  brand: string;
  model: string;
  description?: string | null;
  rating: Decimal;
  type: CarType;
  capacity: number;
  steering: CarSteering;
  gasoline: number;
  price: Decimal;
  discount: number;
  images: string[];
}

export interface ReviewDBModel {
  id: number;
  createdAt: Date;
  title: string;
  content: string;
  rating: number;
  userId: number;
  carId: number;
}

export interface OrderDBModel {
  id: number;
  createdAt: Date;
  name: string;
  phone: string;
  address: string;
  city: string;
  pickup: JsonValue;
  dropoff: JsonValue;
  payment: JsonValue;
  price: Decimal;
  userId: number;
  carId: number;
}

export interface FavoriteDBModel {
  createdAt: Date;
  userId: number;
  carId: number;
}

export interface NotificationDBModel {
  id: number;
  createdAt: Date;
  text: string;
  isSeen: boolean;
  userId: number;
}

export interface CarViewDBModel {
  createdAt: Date;
  userId: number;
  carId: number;
}

export type { Decimal };
export type JsonValue = string | number | boolean | { [key in string]?: JsonValue } | Array<JsonValue> | null;
