server {
  listen 80;
  server_name ${FRONTEND_HOST};

  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name ${FRONTEND_HOST};

  ssl_certificate /etc/nginx/certs/morent.local.pem;
  ssl_certificate_key /etc/nginx/certs/morent.local-key.pem;

  location / {
    proxy_pass ${FRONTEND_URL};
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}

server {
  listen 80;
  server_name ${API_HOST};

  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name ${API_HOST};

  ssl_certificate /etc/nginx/certs/morent.local.pem;
  ssl_certificate_key /etc/nginx/certs/morent.local-key.pem;

  location / {
    proxy_pass ${API_URL};
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
